# Generated by Django 4.0.4 on 2022-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=320)),
                ('pword_hash', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=32)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
