# Generated by Django 4.0.4 on 2022-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_login_rename_pword_hash_account_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=320, unique=True),
        ),
    ]
