# Generated by Django 4.0.4 on 2022-06-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='salt',
        ),
    ]
