# Generated by Django 4.0.4 on 2022-06-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_account_salt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password_hash',
            new_name='password',
        ),
    ]
